### ISSUE TITLE
Block more trackers

### ISSUE THREAD

**Issue by leggett** [OneClickLab/ugly-email-extension#11]
I think blocking email trackers is a public service so I'm sharing the list of over 100 trackers blocked by [Simplify Gmail](https://simplify.substack.com/p/email-trackers-are-spying-on-yousimplify) with you in case it is useful:
https://gist.github.com/leggett/8c2ab9735037cb66c218fdbe898ddf68

Let me know if you think I'm missing any.

**Comment by sonnyt** [comment]
@leggett Woah! Thank you! I am going to add it to the list.

I keep a repo of all the trackers here https://github.com/OneClickLab/ugly-email-trackers

Feel free to contribute!

**Comment by leggett** [comment]
Thanks -- looks like I have all of these except for a variant on MandrillApp.com I didn't have. Adding to my code.

**Comment by leggett** [comment]
FYI: I've added more trackers and moved my code to github.com/leggett/simplify-trackers -- if you ever make use of the list, happy to add Ugly Email to the list of products that make use of it.
