### ISSUE TITLE
Extension marked as unsafe in Chrome Webstore

### ISSUE THREAD

**Issue by jerwarren** [OneClickLab/ugly-email-extension#31]
Today Edge let me know that it disabled the extension because it "contains malware", with a learn more link that sent me to my extensions page where it showed Ugly Email disabled, with this message in red:

"This extension has been turned off as it's been marked unsafe by the Chrome Web Store."

The extension is still visible and installable on the Chrome Webstore, so I'm really curious what's going on here.  I don't see anything indicating it's been marked unsafe.

**Comment by alanjacobmathew** [comment]
As of now the extension works. Please disable and enable it once from the chrome store. Everything will work as normal.

The [issue was mentioned](https://github.com/OneClickLab/ugly-email-extension/issues/27) last week and a solution was provided.

**Comment by Josebalch** [comment]
It works in Google Chrome, but as @jerwarren said, in MS Edge (Chromium) still says it's unsafe even if you uninstall it and reinstall again from Chrome Web Store. And therefore remains disabled.

I'm experiencing the same issue.

**Comment by alanjacobmathew** [comment]
That is weird. For me it's working on Edge (v: 102.0.1245.39) and Brave browser(Chromium). 

![image](https://user-images.githubusercontent.com/33965848/173018043-67ffcb6d-aff2-460e-90b5-3b77aa804d62.png)

**Comment by Josebalch** [comment]
You actually gave me an idea: I updated from Edge 102.0.1245.**33** to latest 102.0.1245.**39** and now it works!

**Comment by Josebalch** [comment]
False alarm, Edge disabled it again:
![image](https://user-images.githubusercontent.com/1812072/173019945-5bb0ccf2-5b32-42a4-a76a-3fb25629022a.png)

☹

**Comment by Josebalch** [comment]
@sonnyt Sure, it's 4.1.1

![image](https://user-images.githubusercontent.com/1812072/173088780-d579fe9e-4a1d-44df-8c07-7d3bf4a76548.png)

**Comment by Josebalch** [comment]
It didn't... disabled again by Edge a couple of minutes later:

![image](https://user-images.githubusercontent.com/1812072/173089478-f52355a3-7ac5-4566-b95b-bc648873ec45.png)

**Comment by Josebalch** [comment]
So far so good, seems completely solved!

**Comment by sonnyt** [comment]
@Josebalch  I am glad to hear. Quick dumb question, I don't use Edge, so I don't know much about this but are you installing the plugin directly from Chrome Web Store or from some sort of Edge Addon store?

**Comment by Josebalch** [comment]
@sonnyt Not dumb at all.
In MS Edge you can install extensions directly from Chrome Web Store, you just need to enable the option "allow extensions from other stores", otherwise, only the official MS Edge store will be allowed.

In a nutshell, I used this link to install it, same as in my Google Chrome (I use both):
https://chrome.google.com/webstore/detail/ugly-email/ldgiafaliifpknmgofiifianlnbgflgj

**Comment by sonnyt** [comment]
@Josebalch ah ok, makes sense. Maybe we should also make Ugly Email available via the official MS Edge addon store. I will look into it. There is an #19 issue about this, so I am guessing it's possible.
