### ISSUE TITLE
Oops… the system encountered a problem (#2014)

### ISSUE THREAD

**Issue by aet08** [OneClickLab/ugly-email-extension#39]
This morning ugly email is causing this error on gmail.

verified by disabling extension, error goes away, turned it back on error reappears.

![image](https://github.com/OneClickLab/ugly-email-extension/assets/15637131/6474805f-1d6a-4a94-ae85-9a49cdd81877)

**Comment by tew42** [comment]
Same here - getting error 2014 on Gmail as of today, traced it to Ugly Email by enabling/disabling all extensions separately.

Many reports on Chrome Web Store of this issue also, seems to be related to a rolling update (since some reports already date back a few days)

**Comment by sonnyt** [comment]
Following it on #38
