### ISSUE TITLE
Limit website data access [Firefox] 

### ISSUE THREAD

**Issue by gautamjain** [OneClickLab/ugly-email-extension#4]
Hi Sonny,

The Firefox extension asks permission to _Access your data for all websites_.  However, the Chrome extension only requires data for `mail.google.com` and `googleusercontent.com`. 

Could the `firefox.json` manifest be modified so that data access is only requested for those two domains?  Would you expect the extension to still work ok?

**Comment by sonnyt** [comment]
@gautamjain new release should fix this :)
