### ISSUE TITLE
Isolated a bug in gmail with Ugly Email extension

### ISSUE THREAD

**Issue by knwpsk** [OneClickLab/ugly-email-extension#8]
I have isolated a bug with the Ugly Email chrome extension.  I'm pretty sure this is the right repo for it?
https://chrome.google.com/webstore/detail/ugly-email/ldgiafaliifpknmgofiifianlnbgflgj

Circumstance:
In gmail, when I'm forwarding or replying to certain emails, as I'm drafting my reply, gmail reports a connection error:
"Oops... the system encountered a problem (#2013). Retrying..."  
If I try to Send the email I'm drafting, Gmail says it couldn't be sent.  
The draft email cannot be saved or sent.
The only remedy is to (copy the text I'm drafting first, and) refresh the chrome tab and start over.  

I painstakingly tested many permutations over 2 days to isolate the cause.  It's clearly caused by UglyEmail; but it only happens on certain emails.  I can't discern WHICH emails, or what is their characteristic... but I can easily reproduce this now, and I do have a particular email candidate for testing that produces the error every time.

I don't know how to get MY email to you for testing -- If I forward the email (with UglyEmail disabled!), then the forwarded message no longer causes the error.  So that's not feasible.

I could do a couple of things:
1. I could "view original" on the broken email and send you the raw content
2. I could tell you how to recreate the broken email on your own.  

Please contact me and we can discuss next steps.

**Comment by sonnyt** [comment]
@knwpsk hey, I just released the open source version, can you try again?

**Comment by knwpsk** [comment]
@sonnyt , sure - where? In the Chrome store?

**Comment by knwpsk** [comment]
@sonnyt nevermind, I found was updated in Chrome store, I updated and re-enabled it... and it's working.  I can no longer reproduce the bug - with the same subject email that I was able to before.
Thanks for the quick turnaround.
